// Each catalog dish has its own illustration in public/images/dishes.
// Keep this allowlist independent of seed data so public menus only load IDs.
export const illustratedDishIds = [
  "lentil-rice-bake",
  "chickpea-potato-casserole",
  "chicken-rice-tray",
  "vegetable-pasta-tray",
  "grilled-lentil-patties",
  "grilled-chickpea-peppers",
  "grilled-tofu-rice",
  "picnic-chickpea-quinoa",
  "picnic-chicken-rice",
  "picnic-lentil-wraps",
  "picnic-bean-corn-wraps",
  "brunch-chickpea-hash",
  "brunch-vegetable-frittata",
  "brunch-avocado-bean-toast",
  "brunch-tofu-scramble",
  "herb-potato-salad",
  "carrot-cabbage-slaw",
  "cucumber-chickpea-salad",
  "grilled-corn",
  "brunch-breakfast-potatoes",
  "brunch-spinach-mushrooms",
  "brunch-citrus-grapes",
  "brunch-apple-side",
  "gathering-fruit-cups",
  "apple-oat-squares",
  "buffet-chickpea-dip",
  "buffet-tomato-skewers",
  "bbq-lemon-herb-sauce",
  "bbq-tomato-sauce",
  "mushroom-hotpot-broth",
  "tomato-hotpot-broth",
  "hotpot-tofu",
  "hotpot-beef-slices",
  "hotpot-chicken-slices",
  "hotpot-mushroom-platter",
  "hotpot-leafy-greens",
  "hotpot-garlic-tamari-sauce",
  "hotpot-ginger-sesame-sauce",
  "chicken-taco-bowl",
  "vegetarian-pasta-bake",
  "gluten-free-pasta-bake",
  "beef-bulgogi-rice-bowl",
  "chickpea-curry",
  "salmon-rice-bowl",
  "build-your-own-taco-night",
  "tofu-vegetable-stir-fry",
  "black-bean-chili",
  "bbq-chicken-skewers",
  "shrimp-fajitas",
  "cucumber-salad",
  "garlic-bread",
  "roasted-vegetables",
  "kimchi-side",
  "steamed-rice",
  "tortilla-chips-side",
  "peanut-sesame-noodles",
  "caprese-skewers",
  "hummus-vegetables",
  "fruit-platter",
  "brownies",
  "mochi-dessert",
  "ice-cream",
  "coconut-rice-pudding",
  "sparkling-water",
  "lemonade",
  "iced-tea",
] as const;

const illustratedDishes = new Set<string>(illustratedDishIds);

export function dishIllustrationSrc(dishId: string): string | undefined {
  return illustratedDishes.has(dishId) ? `/images/dishes/${dishId}.webp` : undefined;
}
